### ISSUE TITLE
Definitions file: Add keywords to trait definitions

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#500]
Add keywords for each trait to definitions.yml file

**Comment by ehwenk** [comment]
I've removed the `on hold` label from this issue, as we need to add keywords to the definitions file before launching the API.

The following file indicates a selection of suggested keywords, in the columns `tissue`, `category` and `other_tags`: 
https://docs.google.com/spreadsheets/d/14cfzPoaWQuk4XHC067M7uK76kdMVtC63EtRPpzp5FcM/edit?usp=sharing

These will be keywords that can be searched on in the API, for users wanting data on clusters of related traits.

Note, that for traits that have been formally reviewed through a workshop, the definitions file can be made much more expansive and there are longer keyword lists linked to ontologies:

https://docs.google.com/document/d/18AXrWp9QrlDXouVDiGgavDem4Fg00aZ5ONNiN9_5aJs/edit

Do we want to merge these longer definitions in for the 25 traits where they are available? @dfalster

**Comment by dfalster** [comment]
@ehwenk - I think we leave this now, as keywords are available separately via the APD. We'd need to demo how to bring these in.

Or would you rather extend the APD link to also pull in keywords?

**Comment by ehwenk** [comment]
No longer think we should have keywords in traits.yml. This issue can be closed
