### ISSUE TITLE
Observation_id: Fix so it works with wide datasets

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#501]
In long datasets, you can fill in a column for observation_id to unite observations on the same individual/site/etc. It is not clear if this is working for wide datasets, because I'd thought that the author's identifier became part of the observation_id code in austraits. A few applications:

- [ ] There are a number of studies where authors provide their own unique identifiers for each study individual and it would be good to retain this information
- [ ] There are studies where different columns of data are measurements on the same individuals, but under different contextual conditions. This is not currently being captured in austraits. For these datasets, the second column with data for a given trait could be bound to the bottom of the first column of trait data, but only if observation id could be used to link the observations back to the same individual. There are similar circumstances where different traits are measured at different sites -i.e. seeds collected in the wild at known lat/lon coordinates, but plants than grown in growth chambers/field experiments.

**Comment by GaryTruong** [comment]
At the moment observation_id is generated using make_id and if an author has their own observation_id this is dropped. Where would you like to retain the original information? 

For the second point, can you provide an example study where you would like this implemented?

**Comment by ehwenk** [comment]
Regarding the first question, I think we need to have a discussion with Daniel about how to treat observation_id - since this is a fundamental identifier in AusTraits and we've never reached a conclusion as to whether the right approach is to maintain the author's "id" column or the AusTraits one. Let's discuss tomorrow at our meeting.

**Comment by ehwenk** [comment]
For the second part, see the data and metadata files for Geange_2017. She's measured the same traits on the same individuals under droughted (e.g. column `Photo_D`) and non-droughted (e.g. column `Photo`) conditions. Right now, only the non-droughted values are being read into AusTraits. We need to make 1 of 2 (or both) changes: Allow wide datasets to also have user-input observation_id column, and then transform her data.csv file, so droughted and non-droughted observations are as several rows with the same column header, but AusTraits keeps track of which pairs of observations were made on the same individual. Or, allow different columns in the dataset to be assigned different contexts. I assume option 1 is easier to implement, since it just requires us to keep track of an author's chosen `observation_id`. 

Right now in a wide dataset, it is assumed that each row has a unique observation_id.

This is a separate issue, from needing to have multiple contextual columns input.

**Comment by ehwenk** [comment]
closed with [4dab6ab](https://github.com/traitecoevo/austraits.build/commit/4dab6abb49ba58ff28dfdfffde20d98064e838dd)
