### ISSUE TITLE
Metadata.yml formatting issues caused by `read_yaml` and/or `write_yaml` functions

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#509]
These may not be possible fixes - but at least we should consider if these issues can be fixed:

- [x]  Make it possible to include special characters in .yml file. This comes up in every study. It means that all "special" characters need to be removed from people's names, but also a lot of time is wasted searching for degree symbols, x, dashes, curly quotes, Greek letters. The biggest problem is that if you miss any and run “metadata_check_taxa” it truncates the metadata file. Lizzy now duplicates the metadata file as soon as she has filled in the basic information to have a backup. 

One solution would be to have a list of all special characters and a function that does an automatic find-and-replace. It would be nice however, if authors names could be correctly spelled.
 
- [ ] Make it possible to add our own paragraph breaks within “sampling strategy” (low priority, but nice for formatting to prevent paragraphs running together)

**Comment by ehwenk** [comment]
First item moved to #513 - there seems to be an easy fix we can implement by switching to the new `read_yaml` and `write_yaml` functions introduced to the `yaml` package.

Second issue can also be fixed, at least in part, with the new functions, by using the `line.sep` or `sep` arguments:
```r
f <- file.path("data", current_study, "metadata.yml")
yaml::read_yaml(f,sep='\n') %>% yaml::write_yaml(f,line.sep='\n')
```
This stops read_yaml from automatically reassigning line breaks after every 80 characters. It means you can introduce your own line breaks in `custom_R_code` and you can introduce paragraph breaks in `sampling_strategy` or `methods` fields. However, there are now no automated line breaks introduced at all, so there are possible flow-on effects to reports or other formatting for very long lines (i.e. a single paragraph under `sampling_strategy`)

There are still some oddities, that are possibly being worked out in the package. The code above, yields the following error:
```r
Error in yaml.load(string, error.label = error.label, ...) : 
  unused argument (sep = "\n")
```
Which refers to the `sep = "\n"` under read_yaml. However, if you remove it, the automated line breaks are added. Meanwhile the `line.sep='\n'` under `write_yaml` appears to have no effect, even though in the package function descriptions, it seems clear that should be included.

**Comment by dfalster** [comment]
See recent updates in #509, with commit 00159e3afd0c8e14958df2e502f98ba5ebd4de70

That commit preserves new lines in custom R code, and adds option to format custom R code with styler package

For the reminder of the file, I've tried to implement a solution, but now think we keep the reformatting of lines and just add a special character when we want a new paragraph. We already did this using `^p` in some places, e.g. https://github.com/traitecoevo/austraits.build/blob/c4517619f5043bac21ac143de5dfc1f7757b3cf2/data/Apgaua_2017/metadata.yml#L41

**Comment by dfalster** [comment]
Further commits on better_yaml branch. Can you review @ehwenk ?

**Comment by ehwenk** [comment]
I'm afraid I'm still having a range of problems - maybe in part because I didn't properly understand what is now "allowed". If I add manual line breaks to `custom_R_code:` I get errors both when running read_metadata/write_metadata and when running tests - for instance after read_metadata/write_metadata, it is hunting for a new label at the start of the new line:
```
 Error in yaml.load(string, error.label = error.label, ...) : 
  (data/Bloomfield_2018/metadata.yml) Scanner error: while scanning a simple key at line 195, column 3 could not find expected ':' at line 196, column 3 
```

Or for `austraits_run_tests`:
```
Backtrace:
  1. testthat::expect_silent(metadata <- read_yaml(f)) test-setup.R:65:2
  9. yaml::read_yaml(f)
 10. yaml::yaml.load(string, error.label = error.label, ...)
------------------------------------------------------
```

And with special characters there are errors I can't make sense of - it seems it won't ever allow two special characters in a row, but in addition if I type them it is creates problems but not if I paste them in. And then once it doesn't like a character in a given line, I suddenly get errors for special characters that previous didn't raise flags. I've tried all different combinations of characters and can't figure out what the trigger is.

**Comment by dfalster** [comment]
This looks good @ehwenk @GaryTruong . 

I agree this is done and we can merge, though tests are failing so need to resolve that before merging.

We can easily convert to paragraph breaks in the report. Let's consider the best way to do that as a separate issue (feel free to post).

**Comment by dfalster** [comment]
latest commit in #517 should fix errors. See https://github.com/traitecoevo/austraits.build/pull/517/commits/834eaa969eb566f33d6e7adc7bd87ffaac8ade50
