### ISSUE TITLE
Previous read_yaml and write_yaml functions truncate files at special characters

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#513]
Migrating issue from issue #488 edits to functions or R scripts.

If there are any "special" characters in a metadata.yml file and you run any function that includes "read_yaml" and/or "write_yaml", such as `metadata_add_substitution()` or `metadata_check_taxa()`, the metadata file is truncated at the first special character.

It seems that this problem has been fixed with the addition of explicit `read_yaml` and `write_yaml` functions to the yaml package. But R code still needs to be updated to switch to these functions.

I first ran tests using the "clear formatting" function, which doesn't truncate, but does replace all special characters with nonsense characters
```
#caused character replacements
f <- file.path("data", current_study, "metadata.yml")
read_yaml(f) %>% write_yaml(f)

#no character replacements
f <- file.path("data", current_study, "metadata.yml")
yaml::read_yaml(f) %>% yaml::write_yaml(f)
```
Then, when the following lines of code in file `setup.R` (starting line 18):
```r
metadata_read_dataset_id <- function(dataset_id) {
  dataset_id %>% metadata_path_dataset_id() %>% read_yaml()
}

metadata_write_dataset_id <- function(metadata, dataset_id) {
  write_yaml(metadata, dataset_id %>% metadata_path_dataset_id())
}
```
Were replaced with this, adding a substitution to a metadata file with species characters no longer caused the file to truncate at the first special character encountered.
```r
metadata_read_dataset_id <- function(dataset_id) {
  dataset_id %>% metadata_path_dataset_id() %>% yaml::read_yaml()
}

metadata_write_dataset_id <- function(metadata, dataset_id) {
  yaml::write_yaml(metadata, dataset_id %>% metadata_path_dataset_id())
}
```

**Comment by ehwenk** [comment]
See also #509 for a related issue with automatic line breaks that can be solved by the new `read_yaml` and `write_yaml` functions.

**Comment by dfalster** [comment]
Hi @ehwenk Does the above commit fix issues? I've imported `read_yaml` and `write_yaml` from yaml, but also 
written new functions `read_metadata` & `write_metadata` which are the preferred way to read and write metadata 

These

- hopefully fixes issues with special characters
- mainatins line breaks and fromatting with custom R code
- add option to format custom R code with styler package
 

You can run them over all metadata using 

```
files <- file.path("data", dir("data"), "metadata.yml")
files %>% purrr::walk(~ read_metadata(.x) %>% write_metadata(.x))
```

**Comment by dfalster** [comment]
Please ensure everything still works!

**Comment by ehwenk** [comment]
To test, I used Choat_2006 and did the following:
* added a few special characters throughout (e.g. é)
* pasted the following text from the pdf straight into `sampling_strategy`. This text has both degree symbols (°), a stylized quote (′ ), and an en-dash (–). I made sure there were several extra line breaks
    The study was undertaken in 2000 and 2001 at Many Peaks
    Range (19°11′ S, 145°45′ E) on the north-eastern coast of Australia.
    The climate is characterized by marked inter- and intraannual
    variation in rainfall. Mean annual rainfall at the study
    site is 1100 mm with over 80% of this rainfall usually occurring
    during the summer wet season (December–March). Annual
    rainfall differed markedly between the two years of study
    (Figure 2).
* pasted the following text into methods, chosen for additional en-dashes and also Psi
Leaf gas exchange, ΨL and canopy area were measured in
three seasonal periods: the wet season (November–March),
the transition from wet season to dry season (April–June) and
the dry season (July–October).

Then I ran the following code:
```r
current_study <- "Choat_2006"
dataset_ids <- current_study
austraits_run_tests()
```
and the output indicates the degree symbol, quote and Psi not accepted
```r
Failure (test-setup.R:64:3): Choat_2006
C:/Users/Lizzy/Documents/GitHub/austraits.build/data/Choat_2006/metadata.yml -- disallowed characters detected: 
	- ln 40:     Range (19Â°11â€² S, 145Â°45â€² E) on the north-eastern coast of Australia.
	- ln 276:     Leaf gas exchange, Î¨L and canopy area were measured in
```

Then if you run,
```r
metadata_add_substitution("Choat_2006","seed_shape","circle","spheroid")
```

- line breaks are now reset throughout the metadata file, at the end of every 80 characters
- the Psi symbol is replaced with its unicode version, <U+03A8>
- degree/en-dashes/quotes remain in the file, and if you run `austraits_run_tests()` again, there are no longer disallowed characters flagged

At the previous step, you could also run, with the same result. 
```r
f <- file.path("data", current_study, "metadata.yml")
read_metadata(f) %>% write_metadata(f)
```

So I think the special characters is as fixed as it ever will be. The line breaks still need some tweaking

**Comment by dfalster** [comment]
Ah we sure we don’t want to just accept and live with the reformatting of lines to 80 chars?

In that case, the workflow should updated so that you run a read-write before committing, to ensure that any reformatting is done at the time of file editting.

The 80char files look better on screen don’t they?

**Comment by ehwenk** [comment]
We can certainly live with the 80char breaks - I'd hoped there would be a way to indicate paragraphs, but it is certainly not necessary.

**Comment by dfalster** [comment]
Do you want the paragraphs in the yaml file, to make it easier for the person inputting/editting, or in an eventual report?

**Comment by ehwenk** [comment]
Most important in the reports, although it would make it much easier for anyone wanting to use the metadata files to look up sampling strategy/methods for a study. We could presumably insert some html coded line breaks that appear in the reports?
