### ISSUE TITLE
Line breaks not recognised in some data.csv files

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#516]
The following study's data.csv files currently have line breaks not recognised by my computer:

- EsperonRodriguez_2019
- EsperonRodriguez_2020
- Gardiner_2019
- Jin_2019
- Moles_2000
- Moles_2011
- Ooi_2007
- Staples_2019
- Taseski_2017
- Wills_2018

Simply going into each data.csv file in a text editor, and deleting the final character and then replacing it fixes the issue, but causes  there to be a very long list of changed lines that will be logged on GitHub - so I haven't committed. But needs to be fixed, because currently I have to drag the changed files back and forth between branches (or stash copies in each branch). Screen shot attached, because line breaks reintroduced when I copy and paste lines from GitHub desktop
![image](https://user-images.githubusercontent.com/8701562/133186002-171d5ede-32a0-4630-af99-d3c14cfb823a.png)

**Comment by dfalster** [comment]
HI Lizzy, I think this is worth fixing. 

Two things going on.

1. The issue with these files is they were saved with the wrong sorts of line endings. Linuc, mac, Windows have historically differed in how that indicate line endings. These files seem to have `\r` whereas the standard is `\n`.  `\r` is an old unix style, so maybe came from caitilin's old laptop? Anyway, I have fixed these on branch via commit above. Can you check this branch runs fine for you and if so, merge it in?
2. 1. I assume you're seeing his on your new machine? Your config for git on old machine probably had some settings which fixed this. 

As noted on https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration If you’re on a Windows machine, set it to true — this converts LF endings into CRLF when you check out code:

``` 
git config --global core.autocrlf true
```

**Comment by ehwenk** [comment]
Yes, that solves the problem.
