### ISSUE TITLE
Standarise site condition names

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#519]
Other than `latitude (deg)`, `longitude (deg)` and `description` there are currently no rules for how column names are designated. This freedom is important since it lets AusTraits import all new metadata associated with a study. However, for site conditions that are entered again and again, there should be a standard format. For instance, there doesn't need to be `elevation (m)`, `elevation`, `elevation (msl)` and more. Same for annual precipitation, rainfall, total soil N, etc. We should create a short table of repeatedly used site conditions, that people can easily reference.

Assigning this to myself to work on.

**Comment by ehwenk** [comment]
I've created a file, currently residing on my computer, that standardises the names of as many site properties as possible. 

Two options to discuss:
1. Do a global search and replace by dataset_id and site_property to align site properties
2. Leave metadata files as they are, but provide the matching table and very simple code that people can use to align site property names themselves.

**Comment by dfalster** [comment]
Great idea. I prefer option 1, as it's simpler long term. But it's more work when entering new studies as you'll need to check against existing names.

We can do the replacement programmatically. 

```

s <- "Falster_2005_1"
from <- "elevation (m)" 
to <- "elev"
f <- file.path("data", s, "metadata.yml")

data <- read_metadata(f)

data$sites

# function to rename single element of list
rename_list_element <- function(my_list, from, to) {
  
  i <- which(names(my_list) == from)
  
  names(my_list)[i] <- to
  
  my_list
}

# rename element in one site
rename_list_element(data$sites$Atherton, from, to)

# rename element in all sites
rename_site_elements <- function(data, from, to) {
  for(s in names(data$sites)) {
    data$sites[[s]] <- data$sites[[s]] %>% rename_list_element(from, to)
  }
  data
}

data <- data %>% rename_site_elements(from, to)

write_metadata(data, f)
```

Might be better to process these after #509 is finished and merged

**Comment by ehwenk** [comment]
I prefer option 1 as well. And thank you for the code - I hadn't reached that step yet, but I have the spreadsheet of changes ready to implement once we've merged in the new read_yaml/write_yaml functions.

**Comment by ehwenk** [comment]
Blocked, waiting for new read_yaml, write_yaml functions to be finalised.

**Comment by ehwenk** [comment]
Aligned all site properties names through commit [ea2615c](https://github.com/traitecoevo/austraits.build/commit/ea2615c708ed2cf3265fdbf26fe6d30b1fd9ff03).

Used the following code to programatically rename site properties based on names in a lookup table. Afterwards a few additional manual changes were made to metadata files.

```read_csv("export/site_property_realignments.csv") %>%
  rename(from = site_property, to = site_property_aligned) -> site_realignments


site_realignments %>% distinct(s) %>% as.data.frame() -> datasets_to_realign

# rename select elements in all sites of all datasets

for(i in 1:nrow(datasets_to_realign)) {
  site_realignments %>% filter(dataset_id == datasets_to_realign[i,1]) -> subset_by_dataset
  dataset__id <- (subset_by_dataset$dataset_id[1])
  
  f <- file.path("data", datasets_to_realign[i,1], "metadata.yml")
  
  data <- read_metadata(f)
  
  for(j in 1:nrow(subset_by_dataset)) {
    from <- as.character(subset_by_dataset[j,2])
    to <- subset_by_dataset[j,3]
    
   for(k in names(data$sites)) {
     
       m <- which(names(data$sites[[k]]) == from)
       
       names(data$sites[[k]])[m] <- to

       data$sites[[k]][m]
   }
    
  }
  
  write_metadata(data, f)
}```
