### ISSUE TITLE
errors in vignettes - technical and content

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#520]
austraits.structure.Rmd
•	Error when knitting, Line 78, str_replace_all not found (Daniel, not sure about this...)

Austraits_raw_data.Rmd
•	Contributor is still defined as, “Person responsible for entering data into AusTraits”, yet throughout metadata files it has been the “Person contributing the data to AusTraits” – we’ve talked about editing this several times and never done that.
•	Under config, “Other allowed values include site_name, observation_id, context_name if these columns are present in the data.csv file or created with custom R code.” Observation_id only accepted for long format at this point (see issue #501)

**Comment by dfalster** [comment]
Recent commit (on the `adding_data` branch) hopefully fixes error

Regarding the other issues, it's unclear what you're asking me to do. Feel free to make edits to align with current situation and understanding.

**Comment by ehwenk** [comment]
In austraits_structure.Rmd,
`austraits$definitions$austraits$elements$build_info$elements$version$value` is called - this is empty - no version number appears, either in the knit html file or when this is searched directly.
@dfalster

**Comment by dfalster** [comment]
Fixed in above commit

**Comment by ehwenk** [comment]
Comments in reference to commit #4f22d84 @dfalster 
- tolower() - is there an equivalent function that just changes the first letter of a string from upper to lower case. There are a number of times tolower() is used, where this would be better. Just doing a single letter substitution doesn't work at least one place, because there are two "A"'s, one of which needs to remain capital - could use a combination of "find first" and "A to a", but maybe there is a less clunky way?
- in austraits_raw_data, an unfilled in section titled 'R'. Should I give that a try or is there a specific format of describing each of the files in R. (Other files, like vignettes, scripts, also not described in this file)
- starting on line #109 of austraits_structure, is a section that seems like it should be integrated into the descriptions higher up in the document. Or is there another purpose for those sections? 
- definitions file has been updated, but even after rebuilding austraits (and re-sourcing functions, in case that matters), the new definitions aren't being incorporated into the documents
- do you mind if I contact Anna Munro to make sure I've now used the correct wording referencing the APC and APNI lists?

**Comment by ehwenk** [comment]
[Contributor Code of Conduct](../.github/CODE_OF_CONDUCT.md) link on line 76 on austraits.build.Rmd is not a correct link. Do we link to Zenodo or a separate code of conduct file? @dfalster

**Comment by ehwenk** [comment]
vignettes fully edited for now, except:

* still pulling in contents from old definitions file 
* in the vignette on the Austraits file structure, only quite broad information on files used by R package
* waiting to merge in a few additional comments on referencing APC/APNI
