### ISSUE TITLE
Data rows being duplicated

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#548]
While looking through flowering time data, I discovered that at least in WAH_1998, a number of rows of data are being read in multiple times. I looked carefully through the `metadata.yml` file, especially at where traits are read in and substitutions and taxonomic updates are made, trying to work out a pattern. The only similarity across names (with 1 exception) is that they are all in the family Orchidaceae, which means the names are being matched to APNI, not APC. I have no idea if this is the cause, but maybe a starting point for understanding the problem. 

All traits for the study are being duplicated

Run the following to see a list of duplicates. 
```
austraits$traits %>% filter(dataset_id == "WAH_1998") %>% group_by(observation_id,trait_name) %>% filter(n()>1) %>% ungroup() -> WAH_1998_duplicates

WAH_1998_duplicates %>% distinct(taxon_name) %>% View()
```

**Comment by ehwenk** [comment]
I've just searched the names on APNI and indeed, this is the source of the error. In each case, the given name appears multiple times in APNI and the number of times the name appears matches the number of duplicates is AusTraits. This is likely to be an issue throughout AusTraits for names matched to APNI. For the Orchidaceae at least this is now solved, since the family has been added to APC, but there will be lingering APNI alignments and so we need to figure out where this is happening. Probably something to solve in conjuction with the other fixes to the taxonomy matching.

**Comment by ehwenk** [comment]
I'm going to add this to a taxonomic updates milestone instead. 

This is a problem that occurs during a join step in taxon matching, that matches a name in the dataset to all instances of that names in APC (or APNI), duplicating data

**Comment by ehwenk** [comment]
This bug came up in conversation with Belinda this morning and I think I've traced it to the `left_join` in this section of code 
```
dplyr::left_join(by = "cleaned_name", taxonomic_resources$APNI %>% 
                       dplyr::filter(.data$nameElement != "sp.") %>%
                       dplyr::select(cleaned_name = .data$canonicalName, taxonIDClean = .data$scientificNameID, 
                                     .data$family, .data$taxonRank))
```

It occurs because there are ~5000 taxa that appear on the APNI list with multiple entries for the same canonicalName (but different authors). So the data being read in are matched to all instances of those names. 

The solution is to change 
  ```  taxonomic_resources$APNI <- read_csv_char(file_paths$APNI) ```

to 
```
    taxonomic_resources$APNI <- 
      read_csv_char(file_paths$APNI) %>%
      distinct(canonicalName, .keep_all = TRUE)
```

**Comment by dfalster** [comment]
Good find Lizzy!

**Comment by ehwenk** [comment]
Second location with a problem... When names matching to the APC & APNI lists are merged to create `taxon_list.csv`, a few names present were being added twice. 

I added ```dplyr::distinct(.data$cleaned_name, .keep_all = TRUE)``` to line 362 in taxonomy.R.

AusTraits now pivots!
