### ISSUE TITLE
metadata_source_doi() not working

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#554]
There seems to be a problem `metadata_source_doi()` due to an update in the package `rcrossref`.

Both Gillian and I received this message when using the function:
```
Error in cr_GET(endpoint = sprintf("works/%s/agency", x), args = list(),  : 
  res$response_headers$`content-type` == "application/json;charset=UTF-8" is not TRUE 
```

**Comment by GaryTruong** [comment]
@ehwenk This issue can potentially be closed as I have implemented a workaround that should be sufficient for now on the `modify_metadata_create_template` branch. The issue does appear to stem from `rcrossref` and they could fix it with updates on their end.

**Comment by ehwenk** [comment]
@GaryTruong Thanks! Let's close it officially as part of the branch merge.
