### ISSUE TITLE
dataset_id: Cheesman_2020 has both observational and experimental component, labelled "field".

### ISSUE THREAD

**Issue by itowers1** [traitecoevo/austraits.build#559]
Hi team,

Just noticed that data from dataset_id Cheesman_2020 has data from both a naturally occurring rainforest plot in the Daintree as well as a paired "throughfall exclusion" water stress plot, but is characterised as "field" only.

`austraits$traits %>% filter(dataset_id == "Cheesman_2020") %>% filter(trait_name == "leaf_delta13C") %>% pull(context_name)`

**Comment by ehwenk** [comment]
Thanks for catching this Isaac. I've just fixed it on the branch where we're dividing collection_types by row, trait or site. Let me know if you catch others - the context is a good place to look.
