### ISSUE TITLE
Increase code coverage of tests

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#582]
Nice work adding code coverage @GaryTruong 

At present we have only 17% coverage, which isn't great. Do you think you can improve this @GaryTruong ?

The codecov website shows some nice diagnostics of what's tested and what's not:

https://codecov.io/gh/traitecoevo/austraits.build/tree/develop/R

It currently says `steps.R` has almost no tests, which isn't exactly true, as these are tested under `tests/build` 

I wonder if we should integrate the subfolders? Or changed which branch the codecov reports on?

**Comment by GaryTruong** [comment]
Yes I can work on improving the code coverage. At the moment isnt codecov reporting on the develop branch? Which other branch would you suggest instead?

**Comment by dfalster** [comment]
Develop branch now up to 55%

![image](https://user-images.githubusercontent.com/3589590/183368497-cf4e79c4-6b4c-4a90-80b1-b9629ced484f.jpeg)

**Comment by dfalster** [comment]
As per recent PR (#598)

![image](https://user-images.githubusercontent.com/3589590/183539827-fbf8b2fd-8a02-4396-9e68-03bdd1c8e9af.jpeg)

I'm going to close this now. The remaining functions have user manual input and are not easily tested.
