### ISSUE TITLE
Rename functions for whole dataset

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#590]
@yangsophieee and I were discussing the name of function `test_data_setup`, the it's not very intuitive. 

Then I noted that function names for whole dataset are inconsistent with metadata. 

for metadata, we have functions like

![image](https://user-images.githubusercontent.com/3589590/179436287-78b437b6-aeba-43c9-9174-682ddfdcc80d.jpeg)

But for whole dataset we have

![image](https://user-images.githubusercontent.com/3589590/179436302-c15901f0-5a0b-459c-a952-744fd0024fd8.png)

Should we rename the whole dataset functions to be things like

`dataset_build`
`dataset_make_report`
`dataset_combine`
`dataset_test_setup`

WDYT @ehwenk @GaryTruong @yangsophieee ?

**Comment by GaryTruong** [comment]
Yeah I think it would be worth changing the names to `dataset_etc` to make it more consistent.

**Comment by yangsophieee** [comment]
That sounds great! Much more consistent and easy to find.
