### ISSUE TITLE
tests on data Outdated (after structural changes) -> update & shift to a function

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/austraits.build#591]
We had some tests to check formatting of a dataset, which are now not working due to recent structural changes. (Thanks @yangsophieee for reporting)

e.g. `library(austraits.build); test_data_setup("Angevin_2011")` reports many false errors

These need to be 

- updated to run effectively 
- converted into a function that can be run, as part of the package (rather than a script in `tests`)

**Comment by dfalster** [comment]
Hi @yangsophieee 

I've updated the tests to work as a function. Can you install this version of package and try it out? 

```
remotes::install_github("traitecoevo/austraits.build@update_dataset_tests")
library(austraits.build)
# test single
dataset_test_setup("Angevin_2011")
# test many
dataset_test_setup(c("Falster_2005_1", "Angevin_2011"))
```

**Comment by yangsophieee** [comment]
Hi @dfalster, everything works great! All tests passed for both studies.
