### ISSUE TITLE
`value_type` has conflicting meanings

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#606]
austraits uses the term "value_type" in 2 very different ways.

- in the definitions.yml file it distinguishes between "categorical" vs "numeric" traits
- in the traits table it indicates if the value is a  "mean, max, min, raw, etc"  value. 
 
ETS uses "valueType" to distinguish between categorical vs numeric, but has "statisticalMethod" for a field that is somewhat similar to our use in the traits table.

**Comment by dfalster** [comment]
Re `value_type`, is `entity_value` a better name?

**Comment by dfalster** [comment]
Re `value_type`, is `entity_value` a better name?

**Comment by ehwenk** [comment]
I don't think it is a good idea to use the word `entity` here. Because it suggests it is a value of the entity (which is what `value` is). Since `entity_type` will be in the same list of terms within the traits table.

What about `value_statistic`?

**Comment by dfalster** [comment]
Yes, except raw isn't a statistic

**Comment by ehwenk** [comment]
I know this has been bugging me too. `value_manipulation`?

**Comment by ehwenk** [comment]
`value_classification

**Comment by ehwenk** [comment]
We have decided to leave `value_type` as is. This means AusTraits has a different means for `value_type` than ETS, but it is the best fit for what the field actually encompasses. 

When we update the traits.yml file later, we will consider changing the term `type` to `trait_type` to clearly differentiate it from `value_type`.
