### ISSUE TITLE
metadata_build_template() not working for long datasets

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#614]
The function `metadata_build_template` works as expected for wide datasets, but for long datasets, it doesn't automatically add traits to the metadata.yml template it creates. This has possibly been a bug for a while, because I believe we've just been testing adding wide datasets.

@payalbal discovered this while attempting to build metadata files using austraits.build for the AusInvertTraits project.

Payal was working off a version of austraits.build from commit 136df0e and I was working off the current develop branch. We both had identical bugs. Payal had the same problem previously, working off a version from early June.

**Comment by dfalster** [comment]
Actually, it doesn't add trait for either wide or long datasets. For that you need to call `metadata_add_traits`. Perhaps this should happen automatically as part of `metadata_create_template`?

**Comment by ehwenk** [comment]
It used to automatically add all traits for long-format datasets. You'd just call `metadata_add_traits` for wide datasets. With a long dataset it would add all trait names that appeared in the designated `traits` column

**Comment by dfalster** [comment]
It may have once done that but doesn't currently
