### ISSUE TITLE
Update testdata.R

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#623]
testdata.R mostly updated to align with new metadata.yml format, but errors remain:

* line 379 - update test to reflect change from `people` to `contributors` format
* line 447 - the allowable elements under traits are those in the schema OR columns that are later read into contexts - and therefore the field in traits is the same as a context `var_in`
* a number of locations flagged as "need to add test"

**Comment by dfalster** [comment]
Needs further updating, to add tests where none exists

**Comment by dfalster** [comment]
Moved to traits.build
