### ISSUE TITLE
units of leaf size for the Ahrens_2019 dataset seem off

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/austraits.build#660]
maybe a conversion problem somewhere?

```r
filter(austraits$traits,taxon_name=="Corymbia calophylla",trait_name=="leaf_area") %>%
     ggplot(aes(y=as.numeric(value),x=dataset_id))+
           geom_boxplot()+
               theme_bw()+
              ylab("leaf_area_mm2")+
               ggtitle("Corymbia calophylla")
```
![image](https://user-images.githubusercontent.com/5534161/215023171-dc0aeb30-e47a-4844-97d6-9c0895a8ba4a.png)

**Comment by wcornwell** [comment]
@ehwenk ?

**Comment by ehwenk** [comment]
@wcornwell I've looked into this and the units are those reported in the spreadsheet and the values in the spreadsheet match the reported values and units in the publication. The leaf areas reported are about 6x larger than others and are for saplings (other studies on adult plants), so I think this is probably correct.

**Comment by dfalster** [comment]
@itowers1 ?

**Comment by itowers1** [comment]
Euclid suggests juvenile leaves much bigger than adult leaves https://apps.lucidcentral.org/euclid/text/entities/corymbia_calophylla.htm#:~:text=Corymbia%20calophylla%20is%20easily%20recognised,fruits%20and%20large%20black%20seeds.

**Comment by wcornwell** [comment]
Hmmm, crazy big juvenile leaves, that's wild.  Anyway, looks like this was also a common garden study. 

how do we see that they're seedlings grown in a common garden?  is that in the context somewhere?

**Comment by ehwenk** [comment]
If you looks at the main austraits$traits table there is a column that is `life_stage` that indicates plant age is `sapling`.  And a column `basis_of_record` which indicates it is a `field_experiment`.

**Comment by wcornwell** [comment]
@ehwenk perfect! thanks!

**Comment by wcornwell** [comment]
@ehwenk I found a column called `collection_type` but can't find `life_stage`.  is that on a newer version than `3.0.2`?

**Comment by ehwenk** [comment]
Yes, you need to download the newest version, 4.0.0 at https://zenodo.org/record/7368074#.Y9cZWX1ByUk
