### ISSUE TITLE
Add functionality: for context, omit values & description from metadata.yml file

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#673]
Currently, each value for a context property and a description for each value are required to be listed in the metadata.yml file in order to be read into austraits. 

This is unnecessary for continuous context properties, where each row of data will have a unique context property and no descriptions are required.

We should have it that all the unique context property values from the specified column are read into austraits even if they are not listed in the metadata.yml file. In these cases, the description will simply remain "unknown".

See Prior_2022 as an example of the very long metadata.yml file that is generated currently

**Comment by dfalster** [comment]
Moved to https://github.com/traitecoevo/traits.build/issues/15
