### ISSUE TITLE
Add functionality: Allow `units` to be read in from a column, instead of being specified as a fixed value for a trait

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#674]
In process.R, many metadata fields can be read in through a column. We have not ever added `units` to this list (see lines 933-942 of process.R). The ausinvertraits project has instances where the same trait is documented in different units within a study. Currently they are having to use `custom_R_code` to align units for a given trait. It would make more sense to be able to specify a column under `metadata$traits$unit_in`

**Comment by ehwenk** [comment]
This is particularly important since if you have long-format data and the `value` column is a mix of numeric and categorical data, you have to spit the dataframe into numeric vs categorical portions before doing any manipulations to the values. See `ABRS_1981` for an example

**Comment by dfalster** [comment]
moved to https://github.com/traitecoevo/traits.build/issues/7
