### ISSUE TITLE
Add functionality: select NA chars

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#675]
In many studies there are "filled characters" used to represent NA. Currently these have to be converted to NA's in the `custom_R_code` using `~ na_if(.x, "character").

This function has gotten fussier with dplyr 1.1.0, no longer allowing mass substitutions across a mix of character and numeric columns. It might be better to specify within the `metadata.yml` file specific characters that are NA's for a given study.

This would be included as another optional field in metadata$dataset, probably appearing right before the `custom_R_code`.

**Comment by dfalster** [comment]
Moved to https://github.com/traitecoevo/traits.build/issues/12
