### ISSUE TITLE
broken link on home page

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/austraits.build#693]
broken link on the home page points to here: http://traitecoevo.github.io/austraits.build/articles/Trait_definitions.html

need to make lower case.  shouldn't be case sensitive but for some reason it's 404ing

**Comment by ehwenk** [comment]
@wcornwell Where did you find that link? Because several months ago we thought we changed all instances of it to http://traitecoevo.github.io/austraits.build/articles/trait_definitions.html but maybe we filled some.

**Comment by wcornwell** [comment]
<img width="1403" alt="Screenshot 2023-05-15 at 2 06 20 pm" src="https://github.com/traitecoevo/austraits.build/assets/5534161/a7e67056-4ac8-4e39-b0a2-7b2cd194cfec">

**Comment by ehwenk** [comment]
This has been fixed
