### ISSUE TITLE
Change error warning for missing trait

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#728]
In `traits$excluded_data`, if a `trait_name` isn't found, the error is `Missing unit conversion`. It should be changed to be `Trait name incorrect` (or similar). 

There are also correct instances of the error `Missing unit conversion`, when it is a missing unit conversion, but the same error is being applied to two different situations.

**Comment by dfalster** [comment]
moved to https://github.com/traitecoevo/traits.build/issues/5
