### ISSUE TITLE
Create more explicit error message for "blank" datasets

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#732]
When there is a dataset that contains no information, usually due to a mistake in trait names being mapped in, you get this error:

```
Error in `dplyr::bind_rows()` at austraits.build/R/process.R:1391:4:
! Can't combine `..1$taxon_name` <character> and `..332$taxon_name` <logical>.
```

The empty dataset can be identified by `dir("data")[332]`

It would be good if you got an error message that had this error pattern, the error explicitly identified the problem for traits.build users outside of the AusTraits team.

**Comment by yangsophieee** [comment]
Moved issue to [traits.build](https://github.com/traitecoevo/traits.build/issues/4).
