### ISSUE TITLE
Contexts not being "used"

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/austraits.build#745]
I noticed in the data for Canham_2023 (on branch), there were not nearly enough plot_id values - there are 77 "elevation values" (plot_id) and 17 "inundation duration" values (also plot_id). Filtering contexts to this study 
```
austraits$contexts %>% filter(dataset_id == "Canham_2023") %>% View()
```
lots of the context values don't have a link_id - and apparently aren't being used, despite appearing in the data.csv file. I'm not at all sure what is happening.

**Comment by yangsophieee** [comment]
Witkowski_1991 also has the same issue. Lizzy figured out that if you change the context column to as.character() in the custom_R_code it solves the issue. This seems like something that can be easily fixed in process.R, probably somewhere around line 426.

**Comment by yangsophieee** [comment]
Moved this issue to [traits.build](https://github.com/traitecoevo/traits.build/issues/2).
