### ISSUE TITLE
Potential data issues

### ISSUE THREAD

**Issue by roblanf** [traitecoevo/austraits.build#775]
The Data Science for Biologists class at ANU had a crack at finding potentially problematic issues in the database. 

Please find attached a list of 22 such potentially problematic values. 

The first six columns are straight from the traits table of AusTraits 4.1.0. The others are the names of the folks in the team that found the potential issues, and the notes that will (hopefully!) help you decide if it's a real issue or not. 

Some (most?) seem cut-and-dried. Others a bit less so. Still, a lot of really good efforts from the 30 students in the class.

Let me know if there are ways we can do this better - it's a first attempt. I am considering making a little shiny app to facilitate this. I think it makes a great (and valuable) teaching tool, but for many classes, including mine, it probably still required a bit more coding and wrangling than is ideal to just get down and dirty with data cleaning.

Rob

[AusTraits potential errors - Sheet1.csv](https://github.com/traitecoevo/austraits.build/files/12696386/AusTraits.potential.errors.-.Sheet1.csv)

**Comment by dfalster** [comment]
Thanks so much team, this is a great contribution. We'll be sure to reviews these points and address the issues in a future release. Stay tuned.
